const mongoose = require('mongoose');
const dotenv = require('dotenv').config();
const Product = require('../models/Product');

const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/jewelleryshop', {
      serverSelectionTimeoutMS: 5000,
      socketTimeoutMS: 45000,
    });
    console.log('MongoDB Connected for seeding');

    await Product.deleteMany({});
    console.log('Products cleared');

    const products = [
      {
        name: 'Eternal Diamond Solitaire Ring',
        description: 'A timeless solitaire ring featuring a brilliant-cut diamond set in 14K white gold.',
        price: 24999,
        discountPrice: 21999,
        stock: 25,
        category: 'Rings',
        subcategory: 'Engagement Rings',
        jewelleryCollection: 'Eternal',
        metal: 'White Gold',
        purity: '14K',
        weight: '2.5g',
        diamondWeight: '1.0ct',
        diamondShape: 'Round',
        diamondClarity: 'VS1',
        diamondColor: 'G',
        images: ['https://placehold.co/600x600?text=Diamond+Ring+1', 'https://placehold.co/600x600?text=Diamond+Ring+2'],
        tags: ['engagement', 'solitaire', 'diamond', 'white-gold'],
        isFeatured: true,
        isBestSeller: true,
        isNewArrival: false,
        rating: 4.8,
        reviews: 128,
      },
      {
        name: 'Heritage Gold Bangle Set',
        description: 'Handcrafted traditional gold bangles with intricate Kundan work, perfect for special occasions.',
        price: 18999,
        stock: 40,
        category: 'Bangles',
        jewelleryCollection: 'Heritage',
        metal: 'Gold',
        purity: '22K',
        weight: '12g',
        images: ['https://placehold.co/600x600?text=Gold+Bangle+1', 'https://placehold.co/600x600?text=Gold+Bangle+2'],
        tags: ['bangles', 'heritage', 'gold', 'traditional'],
        isFeatured: true,
        isBestSeller: true,
        isNewArrival: false,
        rating: 4.7,
        reviews: 95,
      },
      {
        name: 'Blossom Diamond Pendant',
        description: 'A delicate pendant featuring a cluster of small diamonds set in rose gold, symbolizing blooming love.',
        price: 12999,
        discountPrice: 10999,
        stock: 30,
        category: 'Necklaces',
        subcategory: 'Pendant Sets',
        jewelleryCollection: 'Blossom',
        metal: 'Rose Gold',
        purity: '14K',
        weight: '1.8g',
        diamondWeight: '0.5ct',
        diamondShape: 'Round',
        diamondClarity: 'VS2',
        diamondColor: 'H',
        images: ['https://placehold.co/600x600?text=Blossom+Pendant+1', 'https://placehold.co/600x600?text=Blossom+Pendant+2'],
        tags: ['pendant', 'blossom', 'rose-gold', 'diamond'],
        isFeatured: false,
        isBestSeller: false,
        isNewArrival: true,
        rating: 4.6,
        reviews: 64,
      },
      {
        name: 'Celeste Sapphire Drop Earrings',
        description: 'Elegant drop earrings featuring cushion-cut sapphires accented with diamonds in 18K gold.',
        price: 15999,
        stock: 20,
        category: 'Earrings',
        subcategory: 'Diamond Earrings',
        jewelleryCollection: 'Celeste',
        metal: 'Gold',
        purity: '18K',
        weight: '3.2g',
        diamondWeight: '0.75ct',
        diamondShape: 'Cushion',
        diamondClarity: 'SI1',
        diamondColor: 'I',
        images: ['https://placehold.co/600x600?text=Sapphire+Earrings+1', 'https://placehold.co/600x600?text=Sapphire+Earrings+2'],
        tags: ['earrings', 'sapphire', 'celeste', 'gold'],
        isFeatured: false,
        isBestSeller: true,
        isNewArrival: false,
        rating: 4.9,
        reviews: 87,
      },
      {
        name: 'Aura Gold Chain Bracelet',
        description: 'A versatile gold chain bracelet with a secure lobster clasp, suitable for any occasion.',
        price: 8999,
        stock: 50,
        category: 'Bracelets',
        subcategory: 'Chain Bracelets',
        jewelleryCollection: 'Aura',
        metal: 'Gold',
        purity: '14K',
        weight: '4.5g',
        images: ['https://placehold.co/600x600?text=Gold+Bracelet+1', 'https://placehold.co/600x600?text=Gold+Bracelet+2'],
        tags: ['bracelet', 'chain', 'aura', 'gold'],
        isFeatured: false,
        isBestSeller: false,
        isNewArrival: false,
        rating: 4.3,
        reviews: 42,
      },
      {
        name: 'Eternal Three-Stone Engagement Ring',
        description: 'A classic three-stone diamond ring representing past, present, and future in 18K white gold.',
        price: 34999,
        discountPrice: 29999,
        stock: 15,
        category: 'Rings',
        subcategory: 'Engagement Rings',
        jewelleryCollection: 'Eternal',
        metal: 'White Gold',
        purity: '18K',
        weight: '3.1g',
        diamondWeight: '1.5ct total',
        diamondShape: 'Round',
        diamondClarity: 'VS1',
        diamondColor: 'G',
        images: ['https://placehold.co/600x600?text=Three+Stone+Ring+1', 'https://placehold.co/600x600?text=Three+Stone+Ring+2'],
        tags: ['engagement', 'three-stone', 'diamond', 'white-gold'],
        isFeatured: true,
        isBestSeller: false,
        isNewArrival: false,
        rating: 4.9,
        reviews: 156,
      },
      {
        name: 'Blossom Pearl Drop Earrings',
        description: 'Delicate earrings featuring cultured pearls with rose gold accents, perfect for everyday elegance.',
        price: 6999,
        stock: 35,
        category: 'Earrings',
        subcategory: 'Gold Earrings',
        jewelleryCollection: 'Blossom',
        metal: 'Rose Gold',
        purity: '14K',
        weight: '2.1g',
        images: ['https://placehold.co/600x600?text=Pearl+Earrings+1', 'https://placehold.co/600x600?text=Pearl+Earrings+2'],
        tags: ['earrings', 'blossom', 'pearl', 'rose-gold'],
        isFeatured: false,
        isBestSeller: false,
        isNewArrival: true,
        rating: 4.4,
        reviews: 78,
      },
      {
        name: 'Heritage Kundan Bangle',
        description: 'Traditional Kundan bangle with intricate stonework and heritage design, a perfect fusion of tradition and elegance.',
        price: 11999,
        discountPrice: 9999,
        stock: 18,
        category: 'Bangles',
        jewelleryCollection: 'Heritage',
        metal: 'Gold',
        purity: '22K',
        weight: '8.5g',
        images: ['https://placehold.co/600x600?text=Kundan+Bangle+1', 'https://placehold.co/600x600?text=Kundan+Bangle+2'],
        tags: ['bangles', 'kundan', 'heritage', 'traditional'],
        isFeatured: true,
        isBestSeller: true,
        isNewArrival: false,
        rating: 4.6,
        reviews: 112,
      },
    ];

    await Product.insertMany(products);
    console.log(`Seeded ${products.length} products`);

    mongoose.connection.close();
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

seedProducts();
